openapi: 3.1.0
info:
  title: Multi-Character RP API
  version: 1.1.0
  description: 支援單或多角色；沒帶 characters 時預設用 bai
servers:
  - url: https://gpt-role-play.onrender.com/api   # 後端 APIRouter(prefix="/api")
paths:
  /respond:
    post:
      operationId: bai             # 與程式一致
      summary: 讓角色（們）回一句話
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: 你對角色說的話
                characters:
                  type: array
                  items: { type: string }
                  description: （可選）指定要回話的角色 ID 陣列
              required: [message]
      responses:
        '200':
          description: 角色回覆陣列
          content:
            application/json:
              schema:
                type: object
                properties:
                  replies:
                    type: array
                    items:
                      type: object
                      properties:
                        name:  { type: string }
                        reply: { type: string }
                      required: [name, reply]
                required: [replies]
